export const COUNTER_INCREMENT = 'COUNTER_INCREMENT';

export const CHANGE_SEARCH_USERS = 'CHANGE_SEARCH_USERS';
export const FETCH_SEARCH_USERS = 'FETCH_SEARCH_USERS';
export const FETCH_SEARCH_USERS_SUCCESS = 'FETCH_SEARCH_USERS_SUCCESS';
export const FETCH_SEARCH_USERS_ERROR = 'FETCH_SEARCH_USERS_ERROR';

export const INIT_USER_PROFILE = 'INIT_USER_PROFILE';

export const FETCH_USER_PROFILE_INFOS = 'FETCH_USER_PROFILE_INFOS';
export const FETCH_USER_PROFILE_INFOS_SUCCESS = 'FETCH_USER_PROFILE_INFOS_SUCCESS';
export const FETCH_USER_PROFILE_INFOS_ERROR = 'FETCH_USER_PROFILE_INFOS_ERROR';

export const FETCH_USER_PROFILE_REPOSITORIES = 'FETCH_USER_PROFILE_REPOSITORIES';
export const FETCH_USER_PROFILE_REPOSITORIES_SUCCESS = 'FETCH_USER_PROFILE_REPOSITORIES_SUCCESS';
export const FETCH_USER_PROFILE_REPOSITORIES_ERROR = 'FETCH_USER_PROFILE_REPOSITORIES_ERROR';