export const COUNTER_INCREMENT = 'COUNTER_INCREMENT';

export const CHANGE_SEARCH_USERS = 'CHANGE_SEARCH_USERS';
export const FETCH_SEARCH_USERS = 'FETCH_SEARCH_USERS';
export const FETCH_SEARCH_USERS_SUCCESS = 'FETCH_SEARCH_USERS_SUCCESS';
export const FETCH_SEARCH_USERS_ERROR = 'FETCH_SEARCH_USERS_ERROR';

